import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/dist/client/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="hu">
      <body>
        <nav className="navbar">
          <ul>  
            <li><Link href="/">Home</Link></li>
            
            <li className="dropdown">
              <span className="dropbtn">Bérlés</span>
              <div className="dropdown-content">
                <Link href="/BerbeAdas">Bérbe adás</Link>
                <Link href="/Berles">Bérlés</Link>
              </div>
            </li>

            <li className="dropdown">
              <span className="dropbtn">Ingatlan</span>
              <div className="dropdown-content">
                <Link href="/Adas">Adás</Link>
                <Link href="/Vetel">Vétel</Link>
              </div>
            </li>

            <li className="dropdown">
              <span className="dropbtn">Felújítás</span>
              <div className="dropdown-content">
                <Link href="/Arajanlat">Árajánlat</Link>
                <Link href="/Felujitaskerese">Felújítás kérése</Link>
              </div>
            </li>

            <li><Link href="/beosztas">Beosztás</Link></li>   
            <li><Link href="/profil">Profil</Link></li>
            <li><Link href="/admin">Admin</Link></li>
          </ul>
        </nav>

        {/* Ez a rész "cserélődik" majd az aktuális oldal tartalmára */}
        <main>{children}</main>
      </body>
    </html>
  );
}